// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bgshow': string;
  'content': string;
  'content_item': string;
  'content_item_active': string;
  'set': string;
}
declare var cssExports: CssExports;
export = cssExports;
