// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'input': string;
  'inputbox': string;
  'login': string;
  'logo': string;
}
declare var cssExports: CssExports;
export = cssExports;
